version: '3'
services:
    charging_mongo:
        image: mongo:6.0
        ports:
            - 27018:27017
        networks:
            main:
        volumes:
            - ./charging-data:/data/db

    charging:
        image: charging-system-dev
        extra_hosts:
            - "host.docker.internal:172.17.0.1"
            - "proxy.docker:127.0.0.1"

        links:
            - charging_mongo
        depends_on:
            - charging_mongo
        ports:
            - 8006:8006
        networks:
            main:
                aliases:
                    - charging.docker
        environment:
        # MongoDB Configuration
        - BAE_CB_MONGO_SERVER=charging_mongo
        - BAE_CB_MONGO_PORT=27017

        # Service Configuration
        - BAE_SERVICE_HOST=http://proxy.docker:8004/
        - BAE_CB_LOCAL_SITE=http://charging.docker:8006/

        # TMForum APIs - Product Catalog
        - BAE_CB_CATALOG=http://host.docker.internal:8632
        - BAE_CB_RESOURCE_CATALOG=http://host.docker.internal:8636
        - BAE_CB_SERVICE_CATALOG=http://host.docker.internal:8637

        # TMForum APIs - Inventory
        - BAE_CB_INVENTORY=http://host.docker.internal:8642
        - BAE_CB_RESOURCE_INVENTORY=http://host.docker.internal:8641
        - BAE_CB_SERVICE_INVENTORY=http://host.docker.internal:8643

        # TMForum APIs - Party & Ordering
        - BAE_CB_PARTY=http://host.docker.internal:8633
        - BAE_CB_ORDERING=http://host.docker.internal:8639

        # TMForum APIs - Billing & Usage
        - BAE_CB_CUSTOMER_BILL=http://host.docker.internal:8645
        - BAE_CB_BILLING=http://host.docker.internal:8644 # ACCOUNT
        - BAE_CB_USAGE=http://host.docker.internal:8080
        # Roles
        - BAE_LP_OAUTH2_ADMIN_ROLE=admin
        - BAE_LP_OAUTH2_SELLER_ROLE=seller
        - BAE_LP_OAUTH2_CUSTOMER_ROLE=customer
        - BAE_LP_OAUTH2_ORG_ADMIN_ROLE=orgAdmin
        # Payment Configuration
        - BAE_CB_PAYMENT_METHOD=dpas
        - BAE_CB_DPAS_CLIENT_API_URL=http://host.docker.internal:4201/api/payment-start
        - BAE_SERVICE_HOST=http://localhost:4200/

networks:
    main:
        external: true

