services:
  party-catalog:
    image: quay.io/fiware/tmforum-party-catalog:${TM_VERSION}
    ports:
      - 8633:8081
    networks:
      - main
    environment:
      ENDPOINTS_ALL_PORT: 9090
      MICRONAUT_SERVER_PORT: 8081
      MICRONAUT_METRICS_ENABLED: true
      ENDPOINTS_HEALTH_ENABLED: true
      LOGGER_LEVELS_ROOT: INFO
      MICRONAUT_CACHES_ENTITIES_MAXIMUM_SIZE: 1000
      MICRONAUT_CACHES_ENTITIES_EXPIRE_AFTER_WRITE: 2s
      MICRONAUT_CACHES_ENTITIES_EXPIRE_AFTER_ACCESS: 2s
      MICRONAUT_HTTP_SERVICES_READ_TIMEOUT: 30s
      MICRONAUT_HTTP_SERVICES_NGSI_PATH: ngsi-ld/v1
      MICRONAUT_HTTP_SERVICES_NGSI_URL: http://scorpio:9090
      GENERAL_BASEPATH: /
      GENERAL_CONTEXT_URL: https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld
      GENERAL_NGSILDORQUERYVALUE: ","
      GENERAL_NGSILDORQUERYKEY: ","
      GENERAL_ENCLOSEQUERY: false

  service-inventory:
    image: quay.io/fiware/tmforum-service-inventory:${TM_VERSION}
    ports:
      - 8643:8081
    networks:
      - main
    environment:
      ENDPOINTS_ALL_PORT: 9090
      MICRONAUT_SERVER_PORT: 8081
      MICRONAUT_METRICS_ENABLED: true
      ENDPOINTS_HEALTH_ENABLED: true
      LOGGER_LEVELS_ROOT: INFO
      MICRONAUT_CACHES_ENTITIES_MAXIMUM_SIZE: 1000
      MICRONAUT_CACHES_ENTITIES_EXPIRE_AFTER_WRITE: 2s
      MICRONAUT_CACHES_ENTITIES_EXPIRE_AFTER_ACCESS: 2s
      MICRONAUT_HTTP_SERVICES_READ_TIMEOUT: 30s
      MICRONAUT_HTTP_SERVICES_NGSI_PATH: ngsi-ld/v1
      MICRONAUT_HTTP_SERVICES_NGSI_URL: http://scorpio:9090
      GENERAL_BASEPATH: /
      GENERAL_CONTEXT_URL: https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld
      GENERAL_NGSILDORQUERYVALUE: ","
      GENERAL_NGSILDORQUERYKEY: ","
      GENERAL_ENCLOSEQUERY: false

  account:
    image: quay.io/fiware/tmforum-account:${TM_VERSION}
    ports:
      - 8644:8081
    networks:
      - main
    environment:
      ENDPOINTS_ALL_PORT: 9090
      MICRONAUT_SERVER_PORT: 8081
      MICRONAUT_METRICS_ENABLED: true
      ENDPOINTS_HEALTH_ENABLED: true
      LOGGER_LEVELS_ROOT: INFO
      MICRONAUT_CACHES_ENTITIES_MAXIMUM_SIZE: 1000
      MICRONAUT_CACHES_ENTITIES_EXPIRE_AFTER_WRITE: 2s
      MICRONAUT_CACHES_ENTITIES_EXPIRE_AFTER_ACCESS: 2s
      MICRONAUT_HTTP_SERVICES_READ_TIMEOUT: 30s
      MICRONAUT_HTTP_SERVICES_NGSI_PATH: ngsi-ld/v1
      MICRONAUT_HTTP_SERVICES_NGSI_URL: http://scorpio:9090
      GENERAL_BASEPATH: /
      GENERAL_CONTEXT_URL: https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld
      GENERAL_NGSILDORQUERYVALUE: ","
      GENERAL_NGSILDORQUERYKEY: ","
      GENERAL_ENCLOSEQUERY: false

  product-catalog:
    image: quay.io/fiware/tmforum-product-catalog:${TM_VERSION}
    ports:
      - 8632:8081
    networks:
      - main
    environment:
      ENDPOINTS_ALL_PORT: 9090
      MICRONAUT_SERVER_PORT: 8081
      MICRONAUT_METRICS_ENABLED: true
      ENDPOINTS_HEALTH_ENABLED: true
      LOGGER_LEVELS_ROOT: INFO
      MICRONAUT_CACHES_ENTITIES_MAXIMUM_SIZE: 1000
      MICRONAUT_CACHES_ENTITIES_EXPIRE_AFTER_WRITE: 2s
      MICRONAUT_CACHES_ENTITIES_EXPIRE_AFTER_ACCESS: 2s
      MICRONAUT_HTTP_SERVICES_READ_TIMEOUT: 30s
      MICRONAUT_HTTP_SERVICES_NGSI_PATH: ngsi-ld/v1
      MICRONAUT_HTTP_SERVICES_NGSI_URL: http://scorpio:9090
      GENERAL_BASEPATH: /
      GENERAL_CONTEXT_URL: https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld
      GENERAL_NGSILDORQUERYVALUE: ","
      GENERAL_NGSILDORQUERYKEY: ","
      GENERAL_ENCLOSEQUERY: false

  service-catalog:
    image: quay.io/fiware/tmforum-service-catalog:${TM_VERSION}
    ports:
      - 8637:8081
    networks:
      - main
    environment:
      ENDPOINTS_ALL_PORT: 9090
      MICRONAUT_SERVER_PORT: 8081
      MICRONAUT_METRICS_ENABLED: true
      ENDPOINTS_HEALTH_ENABLED: true
      LOGGER_LEVELS_ROOT: INFO
      MICRONAUT_CACHES_ENTITIES_MAXIMUM_SIZE: 1000
      MICRONAUT_CACHES_ENTITIES_EXPIRE_AFTER_WRITE: 2s
      MICRONAUT_CACHES_ENTITIES_EXPIRE_AFTER_ACCESS: 2s
      MICRONAUT_HTTP_SERVICES_READ_TIMEOUT: 30s
      MICRONAUT_HTTP_SERVICES_NGSI_PATH: ngsi-ld/v1
      MICRONAUT_HTTP_SERVICES_NGSI_URL: http://scorpio:9090
      GENERAL_BASEPATH: /
      GENERAL_CONTEXT_URL: https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld
      GENERAL_NGSILDORQUERYVALUE: ","
      GENERAL_NGSILDORQUERYKEY: ","
      GENERAL_ENCLOSEQUERY: false

  resource-catalog:
    image: quay.io/fiware/tmforum-resource-catalog:${TM_VERSION}
    ports:
      - 8636:8081
    networks:
      - main
    environment:
      ENDPOINTS_ALL_PORT: 9090
      MICRONAUT_SERVER_PORT: 8081
      MICRONAUT_METRICS_ENABLED: true
      ENDPOINTS_HEALTH_ENABLED: true
      LOGGER_LEVELS_ROOT: INFO
      MICRONAUT_CACHES_ENTITIES_MAXIMUM_SIZE: 1000
      MICRONAUT_CACHES_ENTITIES_EXPIRE_AFTER_WRITE: 2s
      MICRONAUT_CACHES_ENTITIES_EXPIRE_AFTER_ACCESS: 2s
      MICRONAUT_HTTP_SERVICES_READ_TIMEOUT: 30s
      MICRONAUT_HTTP_SERVICES_NGSI_PATH: ngsi-ld/v1
      MICRONAUT_HTTP_SERVICES_NGSI_URL: http://scorpio:9090
      GENERAL_BASEPATH: /
      GENERAL_CONTEXT_URL: https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld
      GENERAL_NGSILDORQUERYVALUE: ","
      GENERAL_NGSILDORQUERYKEY: ","
      GENERAL_ENCLOSEQUERY: false

  product-ordering:
    image: quay.io/fiware/tmforum-product-ordering-management:${TM_VERSION}
    ports:
      - 8639:8081
    networks:
      - main
    environment:
      ENDPOINTS_ALL_PORT: 9090
      MICRONAUT_SERVER_PORT: 8081
      MICRONAUT_METRICS_ENABLED: true
      ENDPOINTS_HEALTH_ENABLED: true
      LOGGER_LEVELS_ROOT: INFO
      MICRONAUT_CACHES_ENTITIES_MAXIMUM_SIZE: 1000
      MICRONAUT_CACHES_ENTITIES_EXPIRE_AFTER_WRITE: 2s
      MICRONAUT_CACHES_ENTITIES_EXPIRE_AFTER_ACCESS: 2s
      MICRONAUT_HTTP_SERVICES_READ_TIMEOUT: 30s
      MICRONAUT_HTTP_SERVICES_NGSI_PATH: ngsi-ld/v1
      MICRONAUT_HTTP_SERVICES_NGSI_URL: http://scorpio:9090
      GENERAL_BASEPATH: /
      GENERAL_CONTEXT_URL: https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld
      GENERAL_NGSILDORQUERYVALUE: ","
      GENERAL_NGSILDORQUERYKEY: ","
      GENERAL_ENCLOSEQUERY: false

  product-inventory:
    image: quay.io/fiware/tmforum-product-inventory:${TM_VERSION}
    ports:
      - 8642:8081
    networks:
      - main
    environment:
      ENDPOINTS_ALL_PORT: 9090
      MICRONAUT_SERVER_PORT: 8081
      MICRONAUT_METRICS_ENABLED: true
      ENDPOINTS_HEALTH_ENABLED: true
      LOGGER_LEVELS_ROOT: INFO
      MICRONAUT_CACHES_ENTITIES_MAXIMUM_SIZE: 1000
      MICRONAUT_CACHES_ENTITIES_EXPIRE_AFTER_WRITE: 2s
      MICRONAUT_CACHES_ENTITIES_EXPIRE_AFTER_ACCESS: 2s
      MICRONAUT_HTTP_SERVICES_READ_TIMEOUT: 30s
      MICRONAUT_HTTP_SERVICES_NGSI_PATH: ngsi-ld/v1
      MICRONAUT_HTTP_SERVICES_NGSI_URL: http://scorpio:9090
      GENERAL_BASEPATH: /
      GENERAL_CONTEXT_URL: https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld
      GENERAL_NGSILDORQUERYVALUE: ","
      GENERAL_NGSILDORQUERYKEY: ","
      GENERAL_ENCLOSEQUERY: false

  resource-inventory:
    image: quay.io/fiware/tmforum-resource-inventory:${TM_VERSION}
    ports:
      - 8641:8081
    networks:
      - main
    environment:
      ENDPOINTS_ALL_PORT: 9090
      MICRONAUT_SERVER_PORT: 8081
      MICRONAUT_METRICS_ENABLED: true
      ENDPOINTS_HEALTH_ENABLED: true
      LOGGER_LEVELS_ROOT: INFO
      MICRONAUT_CACHES_ENTITIES_MAXIMUM_SIZE: 1000
      MICRONAUT_CACHES_ENTITIES_EXPIRE_AFTER_WRITE: 2s
      MICRONAUT_CACHES_ENTITIES_EXPIRE_AFTER_ACCESS: 2s
      MICRONAUT_HTTP_SERVICES_READ_TIMEOUT: 30s
      MICRONAUT_HTTP_SERVICES_NGSI_PATH: ngsi-ld/v1
      MICRONAUT_HTTP_SERVICES_NGSI_URL: http://scorpio:9090
      GENERAL_BASEPATH: /
      GENERAL_CONTEXT_URL: https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld
      GENERAL_NGSILDORQUERYVALUE: ","
      GENERAL_NGSILDORQUERYKEY: ","
      GENERAL_ENCLOSEQUERY: false

  usage:
    image: quay.io/fiware/tmforum-usage-management:${TM_VERSION}
    ports:
      - 8080:8081
    networks:
      - main
    environment:
      ENDPOINTS_ALL_PORT: 9090
      MICRONAUT_SERVER_PORT: 8081
      MICRONAUT_METRICS_ENABLED: true
      ENDPOINTS_HEALTH_ENABLED: true
      LOGGER_LEVELS_ROOT: INFO
      MICRONAUT_CACHES_ENTITIES_MAXIMUM_SIZE: 1000
      MICRONAUT_CACHES_ENTITIES_EXPIRE_AFTER_WRITE: 2s
      MICRONAUT_CACHES_ENTITIES_EXPIRE_AFTER_ACCESS: 2s
      MICRONAUT_HTTP_SERVICES_READ_TIMEOUT: 30s
      MICRONAUT_HTTP_SERVICES_NGSI_PATH: ngsi-ld/v1
      MICRONAUT_HTTP_SERVICES_NGSI_URL: http://scorpio:9090
      GENERAL_BASEPATH: /
      GENERAL_CONTEXT_URL: https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld
      GENERAL_NGSILDORQUERYVALUE: ","
      GENERAL_NGSILDORQUERYKEY: ","
      GENERAL_ENCLOSEQUERY: false

  customer-bill:
    image: quay.io/fiware/tmforum-customer-bill-management:${TM_VERSION}
    ports:
      - 8645:8080
    networks:
      - main
    environment:
      ENDPOINTS_ALL_PORT: 9090
      MICRONAUT_SERVER_PORT: 8080
      MICRONAUT_METRICS_ENABLED: true
      ENDPOINTS_HEALTH_ENABLED: true
      LOGGER_LEVELS_ROOT: INFO
      MICRONAUT_CACHES_ENTITIES_MAXIMUM_SIZE: 1000
      MICRONAUT_CACHES_ENTITIES_EXPIRE_AFTER_WRITE: 2s
      MICRONAUT_CACHES_ENTITIES_EXPIRE_AFTER_ACCESS: 2s
      MICRONAUT_HTTP_SERVICES_READ_TIMEOUT: 30s
      MICRONAUT_HTTP_SERVICES_NGSI_PATH: ngsi-ld/v1
      MICRONAUT_HTTP_SERVICES_NGSI_URL: http://scorpio:9090
      GENERAL_BASEPATH: /
      GENERAL_CONTEXT_URL: https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld
      GENERAL_NGSILDORQUERYVALUE: ","
      GENERAL_NGSILDORQUERYKEY: ","
      GENERAL_ENCLOSEQUERY: false
      API_EXTENSION_ENABLED: true

networks:
  main:
    external: true
