name: Cross-Repo System Test

on:
  repository_dispatch:
    types:
      - cross-repo-test

jobs:
  run-system-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Testing Repository
        uses: actions/checkout@v3

      - name: first test workflow
        run: |
          echo ${{ toJSON(github.event.client_payload) }}

