name: Cross-Repo System Test

on:
  repository_dispatch:
    types:
      - cross-repo-test

jobs:
  run-system-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Testing Repository
        uses: actions/checkout@v3

      - name: System testing (build + execution)
        env:
          GIT_TOKEN: ${{ secrets.PAT_TEST }}
        run: |
          chmod +x testing.sh
          echo "starting system testing"
          BRANCH_A=${{ github.event.client_payload.branch_A }}
          BRANCH_B=${{ github.event.client_payload.branch_B }}
          BRANCH_FRONTEND=${{ github.event.client_payload.branch_frontend }}
          echo "evaluating branches..."
          echo "Proxy branch: $BRANCH_A"
          echo "Charging branch: $BRANCH_B"
          echo "Frontend branch: $BRANCH_FRONTEND"

          # Set defaults if not provided
          if [[ -z $BRANCH_A ]]; then
            BRANCH_A=master
          fi
          if [[ -z $BRANCH_B ]]; then
            BRANCH_B=master
          fi
          if [[ -z $BRANCH_FRONTEND ]]; then
            BRANCH_FRONTEND=master
          fi

          echo "final proxy branch: $BRANCH_A"
          echo "final charging branch: $BRANCH_B"
          echo "final frontend branch: $BRANCH_FRONTEND"

          ./testing.sh $BRANCH_A ${{ github.event.client_payload.repository_A }} $BRANCH_B ${{ github.event.client_payload.repository_B }} $BRANCH_FRONTEND ${{ github.event.client_payload.repository_frontend }} ${{ github.event.client_payload.tm_version }}

